workflows:
  ios-build:                              # ← TÊN DUY NHẤT ĐỂ CODEMAGIC HIỆN NÚT RIÊNG
    name: SOS-BATTERY iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Clean & Setup
        script: |
          echo "=== CLEAN SIÊU SẠCH iOS ==="
          flutter clean
          rm -rf pubspec.lock ios/Pods ios/Podfile.lock
          flutter pub get
          cd ios
          pod cache clean --all
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa                                 # ← IPA CHÍNH THỨC
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.app.dSYM
      - flutter_drive.log

  android-build:                            # ← TÊN DUY NHẤT CHO ANDROID
    name: SOS-BATTERY Android Build
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.1
    triggering:
      events:
        - push
        - tag
    scripts:
      - name: Clean & Setup
        script: |
          flutter clean
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab   # ← AAB CHÍNH THỨC
      - build/app/outputs/flutter-apk/app-release.apk      # ← BONUS: có luôn APK
      - flutter_drive.log
