workflows:
  ios-build:
    name: SOS-BATTERY iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.1
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
  scripts:
      - name: Clean & Get Dependencies
        script: |
          echo "=== CLEAN SIÊU SẠCH TRƯỚC KHI BUILD ==="
          flutter clean
          rm -rf pubspec.lock ios/Pods ios/Podfile.lock
          flutter pub get
          cd ios && pod install --repo-update && cd ..
      - name: Flutter build iOS (no sign)
        script: |
          flutter build ios --release --no-codesign
      - name: Export IPA using Codemagic tools
        script: |
          xcode-project build-ipa --workspace ios/Runner.xcworkspace --scheme Runner
      artifacts:
      - build/ios/ipa/*.ipa

  android-build:
    name: SOS-BATTERY Android Build
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.1
    triggering:
      events:
        - push
    scripts:
      - name: Clean & Build AAB
        script: |
          echo "=== CLEAN & BUILD AAB ==="
          flutter clean
          flutter pub get
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab    # ← FILE AAB CHÍNH THỨC
      - build/app/outputs/flutter-apk/app-release.apk       # ← BONUS: có luôn APK
      - flutter_drive.log
